name: "Yeni bir alternatif önerisi"
description: "Yeni bir alternatif önerin."
title: "[Alternatif]: "
labels: ["alternatif"]
assignees: []

body:
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatifler"
      description: "Önerdiğiniz alternatif markalar veya çözümler (isteğe bağlı)."
      placeholder: "Örn: Y markasını kullanabilirsiniz."
    validations:
      required: true

  - type: input
    id: brand
    attributes:
      label: "Marka Adı"
      description: "Hangi boykot edilen markaya karşı alternatif öneriyorsunuz?"
      placeholder: "Örn: X Şirketi"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Sebep"
      description: "Bu alternatifi oluşturma nedeninizi açıklayın."
      placeholder: "Neden alternatif öneriyorsunuz?"
    validations:
      required: false